

package org.jetbrains.koog.graph.checker.runners;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.util.KtTestUtil;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link org.jetbrains.koog.graph.checker.GenerateTestsKt}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("compiler-plugin/testData/diagnostics")
@TestDataPath("$PROJECT_ROOT")
public class JvmDiagnosticTestGenerated extends AbstractJvmDiagnosticTest {
  private void run(String fileName) {
    runTest("compiler-plugin/testData/diagnostics/" + fileName);
  }

  @Test
  public void testAllFilesPresentInDiagnostics() {
    KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler-plugin/testData/diagnostics"), Pattern.compile("^(.+)\\.kt$"), null, true);
  }

  @Test
  @TestMetadata("koogStrategy.kt")
  public void testKoogStrategy() {
    run("koogStrategy.kt");
  }

  @Test
  @TestMetadata("koogStrategyDeadEnd.kt")
  public void testKoogStrategyDeadEnd() {
    run("koogStrategyDeadEnd.kt");
  }

  @Test
  @TestMetadata("koogStrategyDuplicateNames.kt")
  public void testKoogStrategyDuplicateNames() {
    run("koogStrategyDuplicateNames.kt");
  }

  @Test
  @TestMetadata("koogStrategyEdgeTypeMismatch.kt")
  public void testKoogStrategyEdgeTypeMismatch() {
    run("koogStrategyEdgeTypeMismatch.kt");
  }

  @Test
  @TestMetadata("koogStrategyFinishOutgoing.kt")
  public void testKoogStrategyFinishOutgoing() {
    run("koogStrategyFinishOutgoing.kt");
  }

  @Test
  @TestMetadata("koogStrategyFinishUnreachable.kt")
  public void testKoogStrategyFinishUnreachable() {
    run("koogStrategyFinishUnreachable.kt");
  }

  @Test
  @TestMetadata("koogStrategyNamedNodes.kt")
  public void testKoogStrategyNamedNodes() {
    run("koogStrategyNamedNodes.kt");
  }

  @Test
  @TestMetadata("koogStrategyOnCondition.kt")
  public void testKoogStrategyOnCondition() {
    run("koogStrategyOnCondition.kt");
  }

  @Test
  @TestMetadata("koogStrategyOnConditionTransformed.kt")
  public void testKoogStrategyOnConditionTransformed() {
    run("koogStrategyOnConditionTransformed.kt");
  }

  @Test
  @TestMetadata("koogStrategyOnIsInstance.kt")
  public void testKoogStrategyOnIsInstance() {
    run("koogStrategyOnIsInstance.kt");
  }

  @Test
  @TestMetadata("koogStrategyShadowedEdge.kt")
  public void testKoogStrategyShadowedEdge() {
    run("koogStrategyShadowedEdge.kt");
  }

  @Test
  @TestMetadata("koogStrategyTransformed.kt")
  public void testKoogStrategyTransformed() {
    run("koogStrategyTransformed.kt");
  }

  @Test
  @TestMetadata("koogStrategyUnreachableNode.kt")
  public void testKoogStrategyUnreachableNode() {
    run("koogStrategyUnreachableNode.kt");
  }

  @Test
  @TestMetadata("koogStrategyValidTransform.kt")
  public void testKoogStrategyValidTransform() {
    run("koogStrategyValidTransform.kt");
  }
}
